### ISSUE TITLE
response.body bigger than 32000 bytes

### ISSUE THREAD

**Issue by mlstoppa** [danlong005/RPGWEB#12]
response.body is 32000 bytes in length. In case, and it's my case, the body needs being bigger than this, what solution would you suggest?
I haven't checked what does changing the size of this variable mean to the whole procedure; I would ask for your ideas first.
If there is a reason why it can't be changed I will implement a multiple reads loop instead.

**Comment by mlstoppa** [comment]
I'll try a customized version where response.body is up to 1Mb in size.

**Comment by danlong005** [comment]
I am afraid I would need more information before I could offer an idea. You could perhaps split it up into pages of the response.

**Comment by mlstoppa** [comment]
I mean, response body length does not really have a limit in size, except the browser's limit, which AFAIK seems to be not less than 2M, so I suppose a change can be made to enlarge body dimension at least in response.  Anyway, I will implement a pages response. I am not an expert but it may be a good solution in any case so the server can serve more requests in the same amount of time.
